### ISSUE TITLE
Trying to fix this issue - Drovosek01 (Help?)

### ISSUE THREAD

**Issue by ewotions4** [ewotions4/Issues-with-Adobe-Packager-#1]
Hi @Drovosek01 - I'm having this issue when I run Adobe

When I run the code, I get this error. Any thoughts on what's going on?

Last login: Tue Jul 23 20:59:32 on ttys000
/Users/ewoma/adobe-packager/ccdl.command ; exit;                                
ewoma@Ewomas-MacBook-Pro ~ % /Users/ewoma/adobe-packager/ccdl.command ; exit;
python3 found!
requests 2.28.2 found!
starting ccdl
=================================
= Adobe macOS Package Generator =
============= 0.2.0 =============

Please enter the URL version(v4/v5/v6) for downloading products.xml, or nothing for v6: v4

Downloading products.xml

Source URL is: https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm&channel=sti&platform=osx10-64,osx10,macarm64,macuniversal&productType=Desktop
Traceback (most recent call last):
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/urllib3/connectionpool.py", line 1060, in _validate_conn
    conn.connect()
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x10b68e900>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/urllib3/connectionpool.py", line 801, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='prod-rel-ffc-ccm.oobesaas.adobe.com', port=443): Max retries exceeded with url: /adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm&channel=sti&platform=osx10-64,osx10,macarm64,macuniversal&productType=Desktop (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10b68e900>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ewoma/adobe-packager/./ccdl.py", line 766, in <module>
    products, cdn, sapCodes, allowedPlatforms = get_products()
                                                ^^^^^^^^^^^^^^
  File "/Users/ewoma/adobe-packager/./ccdl.py", line 491, in get_products
    products_xml = get_products_xml(adobeurl)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ewoma/adobe-packager/./ccdl.py", line 274, in get_products_xml
    return ET.fromstring(r(adobeurl))
                         ^^^^^^^^^^^
  File "/Users/ewoma/adobe-packager/./ccdl.py", line 266, in r
    req = session.get(url, headers=headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ewoma/Library/Python/3.12/lib/python/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='prod-rel-ffc-ccm.oobesaas.adobe.com', port=443): Max retries exceeded with url: /adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm&channel=sti&platform=osx10-64,osx10,macarm64,macuniversal&productType=Desktop (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10b68e900>: Failed to establish a new connection: [Errno 61] Connection refused'))

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Drovosek01** [comment]
Lol
You create repository only for publish error log?
You can post it here - https://github.com/Drovosek01/adobe-packager/issues
But add more details
Just crash log is useless

**Comment by ewotions4** [comment]
Sorry, I don't use github often and didn't know how to add issues. I will add to the issues link with details
